export const employeesList = [
  {
    id: 1,
    fullname: "Дмитрий Моисеенко",
    email: "majest228@gmail.com",
    gender: "Мужской",
    birthday: "2001-03-15",
    fullAge: 25,
    position: "Разработчик",
  },
  {
    id: 2,
    fullname: "Айгерим Ахметова",
    email: "aigerim.akhmetova@example.com",
    gender: "Женский",
    birthday: "1998-11-20",
    fullAge: 26,
    position: "Аналитик данных",
  },
  {
    id: 3,
    fullname: "Иван Петров",
    email: "ivan.petrov@example.com",
    gender: "Мужской",
    birthday: "1995-05-10",
    fullAge: 29,
    position: "Системный администратор",
  },
  {
    id: 4,
    fullname: "Сауле Нурмаганбетова",
    email: "saule.nur@example.com",
    gender: "Женский",
    birthday: "1993-07-08",
    fullAge: 31,
    position: "Проектный менеджер",
  },
  {
    id: 5,
    fullname: "Ербол Серикулы",
    email: "erbol.serikuly@example.com",
    gender: "Мужской",
    birthday: "1990-02-18",
    fullAge: 34,
    position: "DevOps инженер",
  },
  {
    id: 6,
    fullname: "Алина Тимирбаева",
    email: "alina.tim@example.com",
    gender: "Женский",
    birthday: "2000-09-01",
    fullAge: 24,
    position: "UI/UX дизайнер",
  },
  {
    id: 7,
    fullname: "Марат Омаров",
    email: "marat.omarov@example.com",
    gender: "Мужской",
    birthday: "1988-12-03",
    fullAge: 36,
    position: "Тестировщик",
  },
  {
    id: 8,
    fullname: "Надежда Ким",
    email: "nadezhda.kim@example.com",
    gender: "Женский",
    birthday: "1992-04-27",
    fullAge: 32,
    position: "Бизнес-аналитик",
  },
];
